language: scala

before_install:
 - travis_retry sudo add-apt-repository ppa:eyecreate/haxe -y
 - travis_retry sudo apt-get update -qq
 - travis_retry git clone --recursive --depth 1 --branch last-compilable-version https://github.com/qifun/haxe.git
 - (cd haxe && make && sudo make install)
 - travis_retry sudo haxelib setup .haxelib
 - travis_retry sudo haxelib install hxjava

scala:
  - 2.10.4
  - 2.11.2

jdk:
  - oraclejdk7
  - openjdk7

matrix:
  allow_failures:
    - scala: 2.10.4
  
